"""create initial 3-layer schema

Revision ID: f320f194a537
Revises: 
Create Date: 2026-05-03 22:46:39.072470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f320f194a537'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_batch_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_file_batch_id'), 'raw_records', ['file_batch_id'], unique=False)
    op.create_index(op.f('ix_raw_records_ingested_at'), 'raw_records', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_raw_records_source'), 'raw_records', ['source'], unique=False)
    op.create_table('normalized_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_record_id', sa.Uuid(), nullable=False),
    sa.Column('owner_name_normalized', sa.String(length=512), nullable=True),
    sa.Column('entity_type', sa.Enum('individual', 'business', 'estate', 'unknown', name='entity_type'), nullable=False),
    sa.Column('address_line1', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=8), nullable=True),
    sa.Column('zip', sa.String(length=16), nullable=True),
    sa.Column('claim_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('property_type', sa.String(length=128), nullable=True),
    sa.Column('record_age_years', sa.Integer(), nullable=True),
    sa.Column('keywords_found', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_normalized_dedup_unique', 'normalized_records', ['dedup_hash'], unique=True, postgresql_where=sa.text('dedup_hash IS NOT NULL'))
    op.create_index(op.f('ix_normalized_records_city'), 'normalized_records', ['city'], unique=False)
    op.create_index(op.f('ix_normalized_records_claim_amount'), 'normalized_records', ['claim_amount'], unique=False)
    op.create_index(op.f('ix_normalized_records_dedup_hash'), 'normalized_records', ['dedup_hash'], unique=False)
    op.create_index(op.f('ix_normalized_records_entity_type'), 'normalized_records', ['entity_type'], unique=False)
    op.create_index(op.f('ix_normalized_records_owner_name_normalized'), 'normalized_records', ['owner_name_normalized'], unique=False)
    op.create_index(op.f('ix_normalized_records_raw_record_id'), 'normalized_records', ['raw_record_id'], unique=False)
    op.create_index(op.f('ix_normalized_records_source'), 'normalized_records', ['source'], unique=False)
    op.create_table('scored_leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('normalized_record_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority'), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exported_to_crm', sa.Boolean(), nullable=False),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('airtable_record_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_record_id'], ['normalized_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scored_leads_exported_to_crm'), 'scored_leads', ['exported_to_crm'], unique=False)
    op.create_index(op.f('ix_scored_leads_normalized_record_id'), 'scored_leads', ['normalized_record_id'], unique=True)
    op.create_index(op.f('ix_scored_leads_priority'), 'scored_leads', ['priority'], unique=False)
    op.create_index(op.f('ix_scored_leads_score'), 'scored_leads', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scored_leads_score'), table_name='scored_leads')
    op.drop_index(op.f('ix_scored_leads_priority'), table_name='scored_leads')
    op.drop_index(op.f('ix_scored_leads_normalized_record_id'), table_name='scored_leads')
    op.drop_index(op.f('ix_scored_leads_exported_to_crm'), table_name='scored_leads')
    op.drop_table('scored_leads')
    op.drop_index(op.f('ix_normalized_records_source'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_raw_record_id'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_owner_name_normalized'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_entity_type'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_dedup_hash'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_claim_amount'), table_name='normalized_records')
    op.drop_index(op.f('ix_normalized_records_city'), table_name='normalized_records')
    op.drop_index('ix_normalized_dedup_unique', table_name='normalized_records', postgresql_where=sa.text('dedup_hash IS NOT NULL'))
    op.drop_table('normalized_records')
    op.drop_index(op.f('ix_raw_records_source'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_ingested_at'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_file_batch_id'), table_name='raw_records')
    op.drop_table('raw_records')
    # ### end Alembic commands ###
